/**
 * Created by sunil on 3/1/18.
 */
import {Color} from './Color'
import {Constant} from './Constants'

export var CompanyInfo = {
    data : [
        {
            name:'Apple',
            level:5,
            website:'https://www.apple.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }

            ],
        },
        {
            name:'Google',
            level:5,
            website:'https://www.google.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },

            ],

        },
        {
            name:'Calibraint',
            level:5,
            website:'http://www.calibraint.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'CALIBRAINT',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'CALIBRAINT',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }
            ],

        },
        {
            name:'Facebook',
            level:5,
            website:'https://www.facebook.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',

                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }
            ],
        },
        {
            name:'Apple',
            level:5,
            website:'https://www.apple.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }

            ],
        },
        {
            name:'Google',
            level:5,
            website:'https://www.google.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },

            ],

        },
        {
            name:'Calibraint',
            level:5,
            website:'http://www.calibraint.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'CALIBRAINT',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'CALIBRAINT',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }
            ],

        },
        {
            name:'Facebook',
            level:5,
            website:'https://www.facebook.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }
            ],
        },
        {
            name:'Apple',
            level:5,
            website:'https://www.apple.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Apple',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }

            ],
        },
        {
            name:'Google',
            level:5,
            website:'https://www.google.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Google',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },

            ],

        },
        {
            name:'Calibraint',
            level:5,
            website:'http://www.calibraint.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'CALIBRAINT',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'CALIBRAINT',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }
            ],

        },
        {
            name:'Facebook',
            level:5,
            website:'https://www.facebook.com',
            jobs: [
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationPostponed,
                    backgroundColor:Color.postponed,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationRSVP,
                    backgroundColor:Color.rsvp,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationApproved,
                    backgroundColor:Color.approved,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                },
                {
                    applicationStatus:Constant.applicationCancelled,
                    backgroundColor:Color.cancelled,
                    updatedTime:'53mins ago',
                    organization:'Facebook',
                    designation:'JavaScript Developer',
                    skills:'JavaScript, WebStorm, XML, CSS, HTML, NodeJS, AngularJS',
                    cost:'$100',
                    model:'OG Old Skool LX',
                    name:'Red Dahila',
                }
            ],
        },
    ]
}